import type { Metadata } from 'next';
import './globals.css';
import { primary, secondary, mono, display } from './_ui/font';
import { Header } from '@/widgets/Header/Header';
import { Footer } from '@/widgets/Footer/Footer';
import Script from 'next/script';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${primary.variable} ${secondary.variable} ${mono.variable} ${display.variable} h-full`}
        >
            <body className="flex min-h-full flex-col flex-nowrap items-stretch justify-start font-primary">
                <Header />
                {children}
                <Footer />
            </body>
            <Script
                src="https://kit.fontawesome.com/4a78fda344.js"
                strategy="afterInteractive"
            ></Script>
        </html>
    );
}
